# Copyright (c) 2025 Joan Fabrégat <j@fabreg.at>
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, subject to the conditions in the full MIT License.
# The Software is provided "as is", without warranty of any kind.

name: Build and Push Docker Images with Multiple Models to DockerHub and GHCR

on:
  push:
    branches:
      - deploy
    tags:
      - 'v*'

env:
  DOCKERHUB_IMAGE: "joanfabregat/embedding-service"
  GHCR_IMAGE: "ghcr.io/joanfabregat/embedding-service"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          - name: "bm42"
            dependencies_group: "fastembed"
          - name: "jina"
            dependencies_group: "transformers"
          - name: "e5"
            dependencies_group: "transformers"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Free up disk space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          docker system prune -af
          df -h

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERHUB_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          tags: |
            type=semver,pattern={{version}},prefix=${{ matrix.model.name }}-
            type=semver,pattern={{major}}.{{minor}},prefix=${{ matrix.model.name }}-
            type=sha,prefix=${{ matrix.model.name }}-
            type=raw,value=${{ matrix.model.name }}-latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push Docker image with BuildKit caching
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.GHCR_IMAGE }}:buildcache-${{ matrix.model.name }}
          cache-to: type=registry,ref=${{ env.GHCR_IMAGE }}:buildcache-${{ matrix.model.name }},mode=inline
          build-args: |
            VERSION=${{ github.ref_name }}
            DEPENDENCIES_GROUP=${{ matrix.model.dependencies_group }}
            EMBEDDING_MODEL=${{ matrix.model.name }}
            BUILD_ID=${{ github.run_id }}
            COMMIT_SHA=${{ github.sha }}